# Header
menu:
  - name: 首页 
    path: /
    icon: /images/icon-home.png
  - name: 文档
    path: /doc
    icon: /images/icon-documentation.png
  - name: 实现
    path: /impl
    icon: /images/icon-implementation.png
  - name: 资源
    path: /res
    icon: /images/icon-res.png
  - name: 临床资源
    path: /clin
    icon: /images/icon-clinical.png
  - name: 管理资源
    path: /admin
    icon: /images/icon-administration.png
  - name: 基础体系
    path: /infra
    icon: /images/icon-infrastructure.png
  - name: github
    path: https://github.com/hl7-fhir/hl7-fhir.github.io
    icon: /images/github.png

# Content
excerpt_link:
fancybox: true



# Miscellaneous
google_analytics: UA-50564678-1
favicon: /favicon.png

